plugins = []

[functions]

[functions."*"]

[build]
publish = "/Users/alen/Documents/Claude_Code_Projects/MedX/medx-portal-fresh"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/passes-preview/*"

[headers.values]
Content-Type = "application/vnd.apple.pkpass"
Content-Disposition = "inline"

[[headers]]
for = "/calendar/*"

[headers.values]
Content-Type = "text/calendar; charset=utf-8"

[[headers]]
for = "/passes-live/*"

[headers.values]
Content-Type = "application/vnd.apple.pkpass"
Content-Disposition = "inline"

[[redirects]]
from = "/api"
to = "https://medx-staging.onrender.com/api"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/*"
to = "https://medx-staging.onrender.com/api/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/plexus"
to = "https://medx-staging.onrender.com/plexus"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/plexus/*"
to = "https://medx-staging.onrender.com/plexus/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/forum"
to = "https://medx-staging.onrender.com/forum"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/forum/*"
to = "https://medx-staging.onrender.com/forum/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/apply"
to = "https://medx-staging.onrender.com/apply"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/apply/*"
to = "https://medx-staging.onrender.com/apply/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/evaluate"
to = "https://medx-staging.onrender.com/evaluate"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/evaluate/*"
to = "https://medx-staging.onrender.com/evaluate/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/pay"
to = "https://medx-staging.onrender.com/pay"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/pay/*"
to = "https://medx-staging.onrender.com/pay/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/pass"
to = "https://medx-staging.onrender.com/pass"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/pass/*"
to = "https://medx-staging.onrender.com/pass/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/invite"
to = "https://medx-staging.onrender.com/invite"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/invite/*"
to = "https://medx-staging.onrender.com/invite/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/reset-password"
to = "https://medx-staging.onrender.com/reset-password"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/reset-password/*"
to = "https://medx-staging.onrender.com/reset-password/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/qr"
to = "https://medx-staging.onrender.com/qr"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/qr/*"
to = "https://medx-staging.onrender.com/qr/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/calendar"
to = "https://medx-staging.onrender.com/calendar"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/calendar/*"
to = "https://medx-staging.onrender.com/calendar/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/verify"
to = "https://medx-staging.onrender.com/verify"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/verify/*"
to = "https://medx-staging.onrender.com/verify/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/r"
to = "https://medx-staging.onrender.com/r"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/r/*"
to = "https://medx-staging.onrender.com/r/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/unsubscribe"
to = "https://medx-staging.onrender.com/unsubscribe"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/unsubscribe/*"
to = "https://medx-staging.onrender.com/unsubscribe/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/email-prefs"
to = "https://medx-staging.onrender.com/email-prefs"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/email-prefs/*"
to = "https://medx-staging.onrender.com/email-prefs/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/donate"
to = "https://medx-staging.onrender.com/donate"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/donate/*"
to = "https://medx-staging.onrender.com/donate/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/uploads"
to = "https://medx-staging.onrender.com/uploads"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/uploads/*"
to = "https://medx-staging.onrender.com/uploads/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/f"
to = "https://medx-staging.onrender.com/f"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/f/*"
to = "https://medx-staging.onrender.com/f/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/speaker"
to = "https://medx-staging.onrender.com/speaker"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/speaker/*"
to = "https://medx-staging.onrender.com/speaker/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/__staging"
to = "https://medx-staging.onrender.com/__staging"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/__staging/*"
to = "https://medx-staging.onrender.com/__staging/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/__admin"
to = "https://medx-staging.onrender.com/__admin"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/__admin/*"
to = "https://medx-staging.onrender.com/__admin/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/invite-success"
to = "https://medx-staging.onrender.com/invite-success"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/invite-cancelled"
to = "https://medx-staging.onrender.com/invite-cancelled"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/verify-certificate"
to = "https://medx-staging.onrender.com/verify-certificate"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/building-bridges"
to = "https://medx-staging.onrender.com/building-bridges"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/donor-night"
to = "https://medx-staging.onrender.com/donor-night"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/terms"
to = "https://medx-staging.onrender.com/terms"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/privacy"
to = "https://medx-staging.onrender.com/privacy"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/health"
to = "https://medx-staging.onrender.com/health"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]